name: Pipeline

on: 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t api-img .
        
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name api api-img

      - name: Testt API
        run: curl http://localhost:5000

        
